In [16]:
import pandas as pd
filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/addresses.csv"

def download(url, filename):
    resp = pd.read_csv(url)
    resp.to_csv(filename)
    
download(filename, "addresses.csv")

df = pd.read_csv("addresses.csv", header=None)

In [17]:

df

,0,1,2,3,4,5,6
0,NaN,John,Doe,120 jefferson st.,Riverside,NJ,8075
1,0.0,Jack,McGinnis,220 hobo Av.,Phila,PA,9119
2,1.0,"John ""Da Man""",Repici,120 Jefferson St.,Riverside,NJ,8075
3,2.0,Stephen,Tyler,"7452 Terrace ""At the Plaza"" road",SomeTown,SD,91234
4,3.0,NaN,Blankman,NaN,SomeTown,SD,298
5,4.0,"Joan ""the bone"", Anne",Jet,"9th, at Terrace plc",Desert City,CO,123

In [18]:
df.columns = ['No','First Name','Last Name','Location','City','State','AreaCode']

In [19]:
df

,No,First Name,Last Name,Location,City,State,AreaCode
0,NaN,John,Doe,120 jefferson st.,Riverside,NJ,8075
1,0.0,Jack,McGinnis,220 hobo Av.,Phila,PA,9119
2,1.0,"John ""Da Man""",Repici,120 Jefferson St.,Riverside,NJ,8075
3,2.0,Stephen,Tyler,"7452 Terrace ""At the Plaza"" road",SomeTown,SD,91234
4,3.0,NaN,Blankman,NaN,SomeTown,SD,298
5,4.0,"Joan ""the bone"", Anne",Jet,"9th, at Terrace plc",Desert City,CO,123

In [20]:
df['First Name']

0                     John
1                     Jack
2            John "Da Man"
3                  Stephen
4                      NaN
5    Joan "the bone", Anne
Name: First Name, dtype: object

In [26]:
df.iloc[0,0]

nan

In [27]:
df.loc[0]

No                          NaN
First Name                 John
Last Name                   Doe
Location      120 jefferson st.
City                  Riverside
State                        NJ
AreaCode                   8075
Name: 0, dtype: object

In [28]:
df.loc[[0,1,2],'Last Name']

0         Doe
1    McGinnis
2      Repici
Name: Last Name, dtype: object

In [30]:
import pandas as pd
import numpy as np
df=pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['a', 'b', 'c'])
df

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [31]:
#applying the transform function
df = df.transform(func = lambda x : x + 10)
df

    a   b   c
0  11  12  13
1  14  15  16
2  17  18  19

In [32]:
result = df.transform(func = ['sqrt'])
result

          a         b         c
       sqrt      sqrt      sqrt
0  3.316625  3.464102  3.605551
1  3.741657  3.872983  4.000000
2  4.123106  4.242641  4.358899

In [33]:
import json
person = {
    'first_name' : 'Mark',
    'last_name' : 'abc',
    'age' : 27,
    'address': {
        "streetAddress": "21 2nd Street",
        "city": "New York",
        "state": "NY",
        "postalCode": "10021-3100"
    }
}

with open('person.json', 'w') as f:  # writing JSON object
    json.dump(person, f)

# Serializing json  
json_object = json.dumps(person, indent = 4) 
  
# Writing to sample.json 
with open("sample.json", "w") as outfile: 
    outfile.write(json_object)

In [34]:
filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/file_example_XLSX_10.xlsx"
df = pd.read_excel(filename)

In [35]:
import xml.etree.ElementTree as ET

# create the file structure
employee = ET.Element('employee')
details = ET.SubElement(employee, 'details')
first = ET.SubElement(details, 'firstname')
second = ET.SubElement(details, 'lastname')
third = ET.SubElement(details, 'age')
first.text = 'Shiv'
second.text = 'Mishra'
third.text = '23'

# create a new XML file with the results
mydata1 = ET.ElementTree(employee)
# myfile = open("items2.xml", "wb")
# myfile.write(mydata)
with open("new_sample.xml", "wb") as files:
    mydata1.write(files)

In [39]:
import xml.etree.ElementTree as etree

filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/Sample-employee-XML-file.xml"
xmlfile = pd.read_xml(filename)
xmlfile.to_xml("sample_employee.xml")

In [40]:
tree = etree.parse("sample_employee.xml")
root = tree.getroot()
root