In [1]:
import pandas as pd
# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 28],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(data)
print(df)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

In [3]:
print(df['Name'])

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [4]:
df.iloc[2]

Name        Charlie
Age              35
City    Los Angeles
Name: 2, dtype: object

In [5]:
df.iloc[1]

Name              Bob
Age                30
City    San Francisco
Name: 1, dtype: object

In [8]:
df[['Name','City']]

      Name           City
0    Alice       New York
1      Bob  San Francisco
2  Charlie    Los Angeles
3    David        Chicago

In [10]:
df[0:3]

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

In [16]:
df.tail

<bound method NDFrame.tail of       Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago>