In [1]:
%pip install xlrd openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: openpyxl in c:\programdata\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Read data from CSV file

# csv_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv'
# df = pd.read_csv(csv_path)

import pandas as pd

filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv"

async def download(url, filename):
#    response = await pyfetch(url)
    response = await pd.read_csv(filename)
    if response.status == 200:
        with open(filename, "wb") as f:
            f.write(await response.bytes())


#await download(filename, "Product-sales.csv")
df = pd.read_csv(filename)
df.dtypes

OrderID          int64
Product         object
Category        object
Quantity         int64
Price            int64
Total            int64
OrderDate       object
CustomerCity    object
dtype: object

In [2]:
df

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [48]:
#Numpy
import numpy as np
a = np.array([0,1.1,2.1,3.1,4.1,5.1,6.1,7.2])
np.dot(a)

TypeError: dot() missing 1 required positional argument: 'b'

In [4]:
type(a)
np.__version__

'1.26.4'

In [5]:
a.dtype

dtype('float64')

In [6]:
a[0]=100

In [7]:
a

array([100. ,   1.1,   2.1,   3.1,   4.1,   5.1,   6.1,   7.2])

In [8]:
b = a[2:5]

In [9]:
b

array([2.1, 3.1, 4.1])

In [10]:
a[1:5:3]

array([1.1, 4.1])

In [11]:
a[3:5] = 300, 400

In [12]:
a[2:]

array([  2.1, 300. , 400. ,   5.1,   6.1,   7.2])

In [13]:
a.mean()

102.70000000000002

In [14]:
a.std()

148.21536694958453

In [15]:
a.max()

400.0

In [16]:
a.min()

1.1

In [61]:
import numpy as np
a = [-1,1]
b = [1,1]
dotarr = np.dot(a,b)
t = np.dot(a.T,b)
t

AttributeError: 'list' object has no attribute 'T'

In [18]:
anp = np.array(a)

In [19]:
anp.ndim

2

In [20]:
anp.shape

(3, 3)

In [21]:
anp.cumsum(anp)

TypeError: only integer scalar arrays can be converted to a scalar index

In [22]:
anp.dtype()

TypeError: 'numpy.dtypes.Int32DType' object is not callable

In [54]:
anp.max()

33

In [24]:
anp[0][0]

11

In [25]:
anp[0:3,2]

array([13, 23, 33])

In [26]:
anp[0,0:3]

array([11, 12, 13])

In [55]:
z = 2 * anp

In [56]:
z

array([[22, 24, 26],
       [42, 44, 46],
       [62, 64, 66]])

In [57]:
zdot =np.dot(a,z)
zdot

array([1552, 1624, 1696])

In [30]:
np.sin(zdot)

array([[ 0.05320399,  0.20200227, -0.44397762],
       [-0.27113792, -0.32185074, -0.37165598],
       [ 0.47584185, -0.75703889,  0.93965388]])

In [31]:
z.T

array([[22, 42, 62],
       [24, 44, 64],
       [26, 46, 66]])

In [32]:
anp.reshape(2,3)

ValueError: cannot reshape array of size 9 into shape (2,3)

In [33]:
arr = np.array([1, 2, 3, 4, 5])
arr.reshape(2,3)

ValueError: cannot reshape array of size 5 into shape (2,3)

In [34]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [37]:
df[["OrderID","Product"]]

   OrderID     Product
0        1      Laptop
1        2  Smartphone
2        3  Desk Chair
3        4    Notebook
4        5     Monitor

In [38]:
df.describe()

        OrderID   Quantity       Price       Total
count  5.000000   5.000000    5.000000     5.00000
mean   3.000000   4.200000  370.400000   894.00000
std    1.581139   3.563706  326.543718   783.69637
min    1.000000   1.000000    2.000000    20.00000
25%    2.000000   2.000000  150.000000   300.00000
50%    3.000000   3.000000  300.000000   750.00000
75%    4.000000   5.000000  600.000000  1600.00000
max    5.000000  10.000000  800.000000  1800.00000

In [39]:
df.dropna()

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [43]:
expdf = df[(df["Price"] > 500)]

In [44]:
expdf

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles

In [46]:
df["CustomerCity"].replace("Miami","Austin", inplace = True)
df

C:\Users\frank\AppData\Local\Temp\ipykernel_2320\986466751.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["CustomerCity"].replace("Miami","Austin", inplace = True)

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Austin

In [47]:
df.tail(2)

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Austin

In [50]:
df.iloc[0,0]

1

In [63]:
X=np.array([[1,0],[0,1]]) 
Y=np.array([[2,2],[2,2]]) 
Z=np.dot(X,Y)

In [64]:
Z

array([[2, 2],
       [2, 2]])