<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="300" alt="Skills Network Logo">
    </a>
</p>

# **Hands-on Practice Lab: Importing Dataset - Laptops Pricing**

Estimated time needed: **20** minutes

In this lab, you will practice the process of loading and drawing basic insights on a dataset as learnt through the module. You are being provided with a fresh dataset on 'Laptop Pricing' which will be used for all the practice labs throughout the course.

# Objectives

After completing this lab you will be able to:

 - Import a dataset from a CSV file to a Pandas dataframe
 - Develop some basic insights about the dataset

# Setup

For this lab, we will be using the following libraries:

* `skillsnetwork` for downloading the daataset

*   [`pandas`](https://pandas.pydata.org/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0187ENSkillsNetwork31430127-2021-01-01) for managing the data.
*   [`numpy`](https://numpy.org/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0187ENSkillsNetwork31430127-2021-01-01) for mathematical operations.

### Importing Required Libraries
!pip install pyodide.http

In [11]:


import pandas as pd
import numpy as np

The functions below will download the dataset into your browser:

In [15]:
async def download(url, filename):
    df = pd.read_csv(url)
    df.to_csv(filename)

In [16]:
file_path = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/laptop_pricing_dataset_base.csv"

To obtain the dataset, utilize the download() function as defined above:

In [17]:
await download(file_path, "laptops.csv")
file_name="laptops.csv"

In [18]:
df = pd.read_csv(file_name)

> Note: This version of the lab is working on JupyterLite, which requires the dataset to be downloaded to the interface. While working on the downloaded version of this notebook on their local machines, the learners can simply **skip the steps above**, and simply use the URL directly in the `pandas.read_csv()` function. You can uncomment and run the statements in the cell below.

In [ ]:
#filepath = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/laptop_pricing_dataset_base.csv"
#df = pd.read_csv(filepath, header=None)

<h1> Task #1: </h1>
<h3>Load the dataset to a pandas dataframe named 'df'</h3>
Print the first 5 entries of the dataset to confirm loading.

In [19]:
# Write your code below and press Shift+Enter to execute.
df.head()

   Unnamed: 0  Acer  4  IPS Panel  2  1  5   35.56  1.6  8  256 1.6.1   978
0           0  Dell  3    Full HD  1  1  3  39.624  2.0  4  256   2.2   634
1           1  Dell  3    Full HD  1  1  7  39.624  2.7  8  256   2.2   946
2           2  Dell  4  IPS Panel  2  1  5  33.782  1.6  8  128  1.22  1244
3           3    HP  4    Full HD  2  1  7  39.624  1.8  8  256  1.91   837
4           4  Dell  3    Full HD  1  1  5  39.624  1.6  8  256   2.2  1016

<details><summary>Click here for solution</summary>

```python
df = pd.read_csv(file_name, header=None)
print(df.head())
```
</details>

<h1> Task #2: </h1>
<h3>Add headers to the dataframe</h3>
The headers for the dataset, in sequence, are "Manufacturer", "Category", "Screen", "GPU", "OS", "CPU_core",
"Screen_Size_inch", "CPU_frequency", "RAM_GB", "Storage_GB_SSD", "Weight_kg" and "Price".

Confirm insertion by printing the first 10 rows of the dataset.

<details><summary>Click here for solution</summary>

```python
# create headers list
headers = ["Manufacturer", "Category", "Screen", "GPU", "OS", "CPU_core", "Screen_Size_inch", "CPU_frequency", "RAM_GB", "Storage_GB_SSD", "Weight_kg", "Price"]
df.columns = headers
print(df.head(10))
```
</details>

<h1> Task #3: </h1>
<h3>Replace '?' with 'NaN'</h3>
Replace the '?' entries in the dataset with NaN value, recevied from the Numpy package.

In [23]:
# Write your code below and press Shift+Enter to execute.
headers = ["index","Manufacturer", "Category", "Screen", "GPU", "OS", "CPU_core", "Screen_Size_inch", "CPU_frequency", "RAM_GB", "Storage_GB_SSD", "Weight_kg","Price"] 
df.columns = headers
df.head(10)

,index,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.2,634
1,1,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.2,946
2,2,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
3,3,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837
4,4,Dell,3,Full HD,1,1,5,39.624,1.6,8,256,2.2,1016
5,5,HP,3,Full HD,3,1,5,39.624,1.6,8,256,2.1,1117
6,6,Acer,3,IPS Panel,2,1,5,38.1,1.6,4,256,2.2,866
7,7,Dell,3,Full HD,1,1,5,39.624,2.5,4,256,2.3,812
8,8,Acer,3,IPS Panel,3,1,7,38.1,1.8,8,256,2.2,1068
9,9,Dell,3,Full HD,1,1,7,39.624,1.8,8,256,2.13,975

In [26]:
# Write your code below and press Shift+Enter to execute.
df.replace("?",np.nan, inplace= True)
df.head(10)

,index,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.2,634
1,1,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.2,946
2,2,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
3,3,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837
4,4,Dell,3,Full HD,1,1,5,39.624,1.6,8,256,2.2,1016
5,5,HP,3,Full HD,3,1,5,39.624,1.6,8,256,2.1,1117
6,6,Acer,3,IPS Panel,2,1,5,38.1,1.6,4,256,2.2,866
7,7,Dell,3,Full HD,1,1,5,39.624,2.5,4,256,2.3,812
8,8,Acer,3,IPS Panel,3,1,7,38.1,1.8,8,256,2.2,1068
9,9,Dell,3,Full HD,1,1,7,39.624,1.8,8,256,2.13,975

<details><summary>Click here for solution</summary>

```python
df.replace('?',np.nan, inplace = True)
```
</details>

<h1> Task #4: </h1>
<h3>Print the data types of the dataframe columns</h3>
Make a note of the data types of the different columns of the dataset.

In [27]:
# Write your code below and press Shift+Enter to execute.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             237 non-null    int64
 1   Manufacturer      237 non-null    object
 2   Category          237 non-null    int64
 3   Screen            237 non-null    object
 4   GPU               237 non-null    int64
 5   OS                237 non-null    int64
 6   CPU_core          237 non-null    int64
 7   Screen_Size_inch  233 non-null    object
 8   CPU_frequency     237 non-null    float64
 9   RAM_GB            237 non-null    int64
 10  Storage_GB_SSD    237 non-null    int64
 11  Weight_kg         232 non-null    object
 12  Price             237 non-null    int64
dtypes: float64(1), int64(8), object(4)
memory usage: 24.2+ KB

<details><summary>Click here for solution</summary>

```python
print(df.dtypes)
```
</details>

<h1> Task #5: </h1>
<h3>Print the statistical description of the dataset, including that of 'object' data types.</h3>

In [30]:
# Write your code below and press Shift+Enter to execute.
df.describe(include='all')

,index,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
count,237.000000,237,237.000000,237,237.000000,237.000000,237.000000,233,237.000000,237.000000,237.000000,232,237.000000
unique,NaN,11,NaN,2,NaN,NaN,NaN,9,NaN,NaN,NaN,77,NaN
top,NaN,Dell,NaN,Full HD,NaN,NaN,NaN,39.624,NaN,NaN,NaN,2.2,NaN
freq,NaN,71,NaN,161,NaN,NaN,NaN,89,NaN,NaN,NaN,21,NaN
mean,118.000000,NaN,3.202532,NaN,2.151899,1.059072,5.632911,NaN,2.363291,7.881857,245.738397,NaN,1464.388186
std,68.560193,NaN,0.776450,NaN,0.639556,0.236258,1.243736,NaN,0.409271,2.487845,34.832516,NaN,574.956374
min,0.000000,NaN,1.000000,NaN,1.000000,1.000000,3.000000,NaN,1.200000,4.000000,128.000000,NaN,527.000000
25%,59.000000,NaN,3.000000,NaN,2.000000,1.000000,5.000000,NaN,2.000000,8.000000,256.000000,NaN,1068.000000
50%,118.000000,NaN,3.000000,NaN,2.000000,1.000000,5.000000,NaN,2.500000,8.000000,256.000000,NaN,1333.000000
75%,177.000000,NaN,4.000000,NaN,3.000000,1.000000,7.000000,NaN,2.700000,8.000000,256.000000,NaN,1777.000000
max,236.000000,NaN,5.000000,NaN,3.000000,2.000000,7.000000,NaN,2.900000,16.000000,256.000000,NaN,3810.000000

<details><summary>Click here for solution</summary>

```python
print(df.describe(include='all'))
```
</details>

<h1> Task #6: </h1>
<h3>Print the summary information of the dataset.</h3>

In [31]:
# Write your code below and press Shift+Enter to execute.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             237 non-null    int64
 1   Manufacturer      237 non-null    object
 2   Category          237 non-null    int64
 3   Screen            237 non-null    object
 4   GPU               237 non-null    int64
 5   OS                237 non-null    int64
 6   CPU_core          237 non-null    int64
 7   Screen_Size_inch  233 non-null    object
 8   CPU_frequency     237 non-null    float64
 9   RAM_GB            237 non-null    int64
 10  Storage_GB_SSD    237 non-null    int64
 11  Weight_kg         232 non-null    object
 12  Price             237 non-null    int64
dtypes: float64(1), int64(8), object(4)
memory usage: 24.2+ KB

<details><summary>Click here for solution</summary>

```python
print(df.info())
```
</details>

---

# Congratulations! You have completed the lab

## Authors

[Abhishek Gagneja](https://www.coursera.org/instructor/~129186572)

[Vicky Kuo](https://author.skills.network/instructors/vicky_kuo)

Copyright © 2023 IBM Corporation. All rights reserved.

<!--## Change Log

<!--|Date (YYYY-MM-DD)|Version|Changed By|Change Description|
|-|-|-|-|
|2023-09-15|0.1|Abhishek Gagneja|Initial Version Created|
|2023-09-18|0.2|Vicky Kuo|Reviewed and Revised|--!>